-- Dump of table actions
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "actions";

CREATE TABLE "actions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

COMMENT ON COLUMN "actions"."id" IS '事件ID';
COMMENT ON COLUMN "actions"."user_id" IS '用户';
COMMENT ON COLUMN "actions"."content" IS '事件内容';
COMMENT ON COLUMN "actions"."created_at" IS '创建时间';
COMMENT ON COLUMN "actions"."updated_at" IS '更新时间';


-- Dump of table articles
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "articles";

CREATE TABLE "articles" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pid" integer NOT NULL,
  "doc_id" integer NOT NULL,
  "title" varchar(255) NOT NULL DEFAULT '',
  "user_id" integer NOT NULL,
  "last_user_id" integer NOT NULL,
  "content" text NOT NULL,
  "type" integer NOT NULL,
  "link" varchar(255) NOT NULL DEFAULT '',
  "reference_id" integer NOT NULL DEFAULT 0,
  "edit_type" integer NOT NULL DEFAULT 1,
  "status" integer NOT NULL DEFAULT 1,
  "sort" integer NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE INDEX "idx_articles_created_at" ON "articles" ("created_at");
CREATE INDEX "idx_articles_updated_at" ON "articles" ("updated_at");

COMMENT ON COLUMN "articles"."id" IS '文章ID';
COMMENT ON COLUMN "articles"."pid" IS '文章父ID';
COMMENT ON COLUMN "articles"."doc_id" IS '所属文档ID';
COMMENT ON COLUMN "articles"."title" IS '文章标题';
COMMENT ON COLUMN "articles"."user_id" IS '创建者';
COMMENT ON COLUMN "articles"."last_user_id" IS '最后编辑者';
COMMENT ON COLUMN "articles"."content" IS '文章内容';
COMMENT ON COLUMN "articles"."type" IS '文章类型1文章，2外链，3引用，4分类，5 swagger';
COMMENT ON COLUMN "articles"."link" IS '链接地址，type=2时有效';
COMMENT ON COLUMN "articles"."reference_id" IS '引用ID type = 3时有效';
COMMENT ON COLUMN "articles"."edit_type" IS '编辑器类型 1 markdown， 2 rich';
COMMENT ON COLUMN "articles"."status" IS '文章状态 1正常，2删除';
COMMENT ON COLUMN "articles"."sort" IS '排序,值越小越靠前';
COMMENT ON COLUMN "articles"."created_at" IS '创建时间';
COMMENT ON COLUMN "articles"."updated_at" IS '更新时间';


-- Dump of table documents
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "documents";

CREATE TABLE "documents" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "last_user_id" integer NOT NULL,
  "title" varchar(255) NOT NULL DEFAULT '',
  "domain" varchar(50) NOT NULL DEFAULT '',
  "logo" varchar(100) NOT NULL DEFAULT '',
  "description" varchar(255) NOT NULL DEFAULT '',
  "permission" integer NOT NULL DEFAULT 1,
  "password" varchar(64) NOT NULL DEFAULT '',
  "status" integer NOT NULL DEFAULT 1,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  CONSTRAINT "un_documents_domain" UNIQUE ("domain")
);

CREATE INDEX "idx_documents_created_at" ON "documents" ("created_at");
CREATE INDEX "idx_documents_updated_at" ON "documents" ("updated_at");

COMMENT ON COLUMN "documents"."id" IS '文档ID';
COMMENT ON COLUMN "documents"."user_id" IS '创建者';
COMMENT ON COLUMN "documents"."last_user_id" IS '最后创建者';
COMMENT ON COLUMN "documents"."title" IS '文档标题';
COMMENT ON COLUMN "documents"."domain" IS '文档路径名';
COMMENT ON COLUMN "documents"."logo" IS '文档LOGO';
COMMENT ON COLUMN "documents"."description" IS '文档描述';
COMMENT ON COLUMN "documents"."permission" IS '文档权限1公开2内部公开3不公开';
COMMENT ON COLUMN "documents"."password" IS '文档密码';
COMMENT ON COLUMN "documents"."status" IS '1 正常  2删除';
COMMENT ON COLUMN "documents"."created_at" IS '创建时间';
COMMENT ON COLUMN "documents"."updated_at" IS '更新时间';


-- Dump of table histories
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "histories";

CREATE TABLE "histories" (
  "hid" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id" integer NOT NULL,
  "pid" integer NOT NULL,
  "doc_id" integer NOT NULL,
  "title" varchar(255) NOT NULL DEFAULT '',
  "user_id" integer NOT NULL,
  "last_user_id" integer NOT NULL,
  "content" text NOT NULL,
  "type" integer NOT NULL,
  "link" varchar(255) NOT NULL DEFAULT '',
  "reference_id" integer NOT NULL,
  "edit_type" integer NOT NULL,
  "status" integer NOT NULL,
  "sort" integer NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE INDEX "idx_histories_created_at" ON "histories" ("created_at");
CREATE INDEX "idx_histories_updated_at" ON "histories" ("updated_at");

COMMENT ON COLUMN "histories"."hid" IS '历史记录ID';
COMMENT ON COLUMN "histories"."id" IS '文章ID';
COMMENT ON COLUMN "histories"."pid" IS '文章父ID';
COMMENT ON COLUMN "histories"."doc_id" IS '所属文档ID';
COMMENT ON COLUMN "histories"."title" IS '文章标题';
COMMENT ON COLUMN "histories"."user_id" IS '创建者';
COMMENT ON COLUMN "histories"."last_user_id" IS '最后编辑者';
COMMENT ON COLUMN "histories"."content" IS '文章内容';
COMMENT ON COLUMN "histories"."type" IS '文章类型1文章，2外链，3引用，4分类';
COMMENT ON COLUMN "histories"."link" IS '链接地址，type=3时有效';
COMMENT ON COLUMN "histories"."reference_id" IS '引用ID type = 3时有效';
COMMENT ON COLUMN "histories"."edit_type" IS '编辑器类型 1 markdown， 2 rich';
COMMENT ON COLUMN "histories"."status" IS '文章状态 1正常，2删除';
COMMENT ON COLUMN "histories"."sort" IS '排序';
COMMENT ON COLUMN "histories"."created_at" IS '创建时间';
COMMENT ON COLUMN "histories"."updated_at" IS '更新时间';


-- Dump of table members
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "members";

CREATE TABLE "members" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doc_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  CONSTRAINT "un_doc_user" UNIQUE ("doc_id", "user_id")
);

COMMENT ON COLUMN "members"."doc_id" IS '文档ID';
COMMENT ON COLUMN "members"."user_id" IS '用户ID';


-- Dump of table shares
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "shares";

CREATE TABLE "shares" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL DEFAULT '',
  "domain" varchar(50) NOT NULL DEFAULT '',
  "doc_id" integer NOT NULL,
  "password" varchar(32) NOT NULL DEFAULT '',
  "share_ids" varchar(255) NOT NULL DEFAULT '',
  "user_id" integer NOT NULL,
  "status" integer NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  CONSTRAINT "un_shares_domain" UNIQUE ("domain")
);

COMMENT ON COLUMN "shares"."name" IS '分享名';
COMMENT ON COLUMN "shares"."domain" IS '分享文档路径';
COMMENT ON COLUMN "shares"."doc_id" IS '文档ID';
COMMENT ON COLUMN "shares"."password" IS '分享文档密码';
COMMENT ON COLUMN "shares"."share_ids" IS '分享文章ID，逗号分隔';
COMMENT ON COLUMN "shares"."user_id" IS '创建者';
COMMENT ON COLUMN "shares"."status" IS '1 正常，2删除';
COMMENT ON COLUMN "shares"."created_at" IS '创建时间';
COMMENT ON COLUMN "shares"."updated_at" IS '更新时间';


-- Dump of table users
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "users";

CREATE TABLE "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_name" varchar(50) NOT NULL DEFAULT '',
  "email" varchar(100) NOT NULL DEFAULT '',
  "real_name" varchar(50) NOT NULL DEFAULT '',
  "password" varchar(64) NOT NULL DEFAULT '',
  "avatar" varchar(100) NOT NULL DEFAULT '',
  "status" integer NOT NULL DEFAULT 1,
  "about" varchar(255) NOT NULL DEFAULT '',
  "role" varchar(30) NOT NULL DEFAULT 'user',
  "organization" varchar(50) NOT NULL DEFAULT '',
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  CONSTRAINT "un_email" UNIQUE ("email"),
  CONSTRAINT "un_user_name" UNIQUE ("user_name")
);

COMMENT ON COLUMN "users"."id" IS '用户ID';
COMMENT ON COLUMN "users"."user_name" IS '用户名，用于展示';
COMMENT ON COLUMN "users"."email" IS '邮箱';
COMMENT ON COLUMN "users"."real_name" IS '真实姓名';
COMMENT ON COLUMN "users"."password" IS '密码';
COMMENT ON COLUMN "users"."avatar" IS '用户头像';
COMMENT ON COLUMN "users"."status" IS '1 启用 2停用';
COMMENT ON COLUMN "users"."about" IS '个人简介';
COMMENT ON COLUMN "users"."role" IS '用户角色admin,leader,user';
COMMENT ON COLUMN "users"."organization" IS '部门组织';


-- Dump of table custom
-- ------------------------------------------------------------
DROP TABLE IF EXISTS "custom";

CREATE TABLE "custom" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "nick_name" varchar(255) NOT NULL,
  "status" smallint NOT NULL DEFAULT 1,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  CONSTRAINT "un_custom_name" UNIQUE ("name"),
  CONSTRAINT "un_nick_name" UNIQUE ("nick_name")
);

COMMENT ON TABLE "custom" IS '用户表';
COMMENT ON COLUMN "custom"."id" IS '主键';
COMMENT ON COLUMN "custom"."name" IS '帐号';
COMMENT ON COLUMN "custom"."nick_name" IS '昵称';
COMMENT ON COLUMN "custom"."status" IS '状态';
COMMENT ON COLUMN "custom"."created_at" IS '创建时间';
COMMENT ON COLUMN "custom"."updated_at" IS '更新时间';
